name: Evento 1 - PR

on:
    pull_request:
        branches: [ main ]

permissions:
    contents: read
    pull-requests: write

jobs:
    pruebas-y-comentarios:
        runs-on: ubuntu-latest
        steps:
            - name: 1. Comentar el inicio en el pr
              uses: thollander/actions-comment-pull-request@v3
              with:
                message: "Iniciando pruebas automáticas para este PR..."